<!DOCTYPE html>
<html>
	
	<head>
		
		<meta HTTP-EQUIV="CONTENT-TYPE" CONTENT="text/html; charset=utf-8">
		<meta NAME="AUTHOR" CONTENT="William Tougeron">
		<meta name="DESCRIPTION" content="cfdmsh 4.0 documentation">
		<meta name="keywords" content="cfdmsh, Salome, CFD, Python"/>
		<meta name="copyright" content="tougeron-cfd.com"/>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		
		<link rel="stylesheet" href="../css/style.css" />
		<link rel="icon" type="image/png" href="../icon.png?v=1"/>
		
		<title>
			
			MakeEdgeOffset - cfdmsh
			
		</title>
		
	</head>
	
	<body LANG="en-US" DIR="LTR">

<p><a href="cfdmshfunctions.html"><img alt="picture" src="../pictures/back.png"></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="../index.html"><img alt="picture" src="../pictures/home.png"></a>&nbsp;&nbsp;&nbsp;<strong>cfdmsh 4.0 documentation</strong></p>

<p><a href="makefoilfromunsortedvertexes.html"><img alt="picture" src="../pictures/left.png"/> </a> &nbsp;&nbsp; <a href="makeplanarwireoffset.html"><img alt="picture" src="../pictures/right.png"/></a></p>

<h2>MakeEdgeOffset</h2>

<h3 id="short_description">Short Description &nbsp;&nbsp;<a href="#"><img alt="picture" src="../pictures/up.png"/></a></h3>

<p>Creates an offset of an edge.</p>

<h3 id="long_description">Additional Information &nbsp;&nbsp;<a href="#"><img alt="picture" src="../pictures/up.png"/></a></h3>

<p>This function first extrudes the input edge so as to have a face from which 
to create normal vectors defining the offset direction at each position 
along the edge.
The extrusion direction is given by the input edge plane normal. This plane 
is by default created by closing the input edge with an additional edge linking its boundaries 
and by creating a planar face from these two edges. 
Then, many vertexes are created along the input edge and translated following 
local normal vectors. Then, a spline is created from this set of 
translated vertexes.</p>
 
<p>The offset can be "closed", that is two additional edges linking the boundaries of both source edge
and offset can be added.</p>

<p>The user can also ask for creating a face linking the input edge to the offset.</p>

<h3 id="definition">Definition &nbsp;&nbsp;<a href="#"><img alt="picture" src="../pictures/up.png"/></a></h3>

 

<p class="code">def MakeEdgeOffset( dist, edge = None, pos = [0, 1], face = None, plane = None, np = 20, curv = True, close = False, rebuild = True, tol = 1e-7, rev = False, single = True, add = True, infa = False, dim = 1 ):</p>

 

<p><img alt="picture" src = "../pictures/makeedgeoffset_1.png"></p>
<p><img alt="picture" src="../pictures/makeedgeoffset_2.png"></p>
<p><img alt="picture" src="../pictures/makeedgeoffset_3.png"></p>

<h3 id="arguments">Argument(s) &nbsp;&nbsp;<a href="#"><img alt="picture" src="../pictures/up.png"/></a></h3>

<table class="arguments">

<tr>
<th>Name</th>
<th>Description</th>
<th>Type</th>
<th>GUI selection <span class="info"><a href="use.html#selection">[?]</a></span></th>
<th>Selection by name <span class="info"><a href="use.html#name">[?]</a></span></th>
<th>Recursive <span class="info"><a href="use.html#recursivefunctions">[?]</a></span></th>
<th>Default value</th>
</tr>

<tr>
<td><em>dist</em></td>
<td>The offset distance. Must be an list to create a variable offset.</td>
<td><strong>Float</strong> or <br/> <strong>List</strong> of <br/> <strong>Floats</strong></td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>-</td>
</tr>

<tr>
<td><em>edge</em></td>
<td>The input edge.</td>
<td><strong>Edge</strong></td>
<td>yes</td>
<td>yes</td>
<td>yes</td>
<td>None</td>
</tr>

<tr>
<td><em>pos</em></td>
<td>The positions on the source edge (0 &lt; <em>pos</em> &lt; 1).<br/>
Only necessary if the <em>dist</em> 
argument is an list.</td>
<td><strong>List</strong> of <br/> <strong>Floats</strong></td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>[0,1]</td>
</tr>

<tr>
<td><em>face</em></td>
<td>See <a href="commonarguments.html#face">here</a>.</td>
<td><strong>Face</strong></td>
<td>-</td>
<td>yes</td>
<td>-</td>
<td>None</td>
</tr>

<tr>
<td><em>plane</em></td>
<td>See <a href="commonarguments.html#plane">here</a>. If the input edge is straight, the default plane is the OXY plane.</td>
<td><strong>Face</strong></td>
<td>-</td>
<td>yes</td>
<td>-</td>
<td>None</td>
</tr>

<tr>
<td><em>np</em></td>
<td>See <a href="commonarguments.html#np">here</a>.</td>
<td><strong>Integer</strong></td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>50</td>
</tr>

<tr>
<td><em>curv</em></td>
<td>See <a href="commonarguments.html#curv">here</a>.</td>
<td><strong>Boolean</strong></td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>True</td>
</tr>

<tr>
<td><em>rebuild</em></td>
<td>In case <em>dim</em> = 2, defines if the input edge has to be rebuilt in the same way than the offset edge.</td>
<td><strong>Boolean</strong></td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>True</td>
</tr>

<tr>
<td><em>close</em></td>
<td>If equals True, the offset edge is linked to the source edge by two additional edges.</td>
<td><strong>Boolean</strong></td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>False</td>
</tr>

<tr>
<td><em>tol</em></td>
<td>See <a href="commonarguments.html#tol">here</a>.</td>
<td><strong>Float</strong></td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>1e-7</td>
</tr>

<tr>
<td><em>rev</em></td>
<td>See <a href="commonarguments.html#rev">here</a>.</td>
<td><strong>Boolean</strong></td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>False</td>
</tr>

<tr>
<td><em>single</em></td>
<td>See <a href="commonarguments.html#single">here</a>.</td>
<td><strong>Boolean</strong></td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>True</td>
</tr>

<tr>
<td><em>add</em></td>
<td>See <a href="commonarguments.html#add">here</a>.</td>
<td><strong>Boolean</strong></td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>True</td>
</tr>

<tr>
<td><em>infa</em></td>
<td>See <a href="commonarguments.html#infa">here</a>.</td>
<td><strong>Boolean</strong></td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>False</td>
</tr>

<tr>
<td><em>dim</em></td>
<td>See <a href="commonarguments.html#dim">here</a>.</td>
<td><strong>Integer</strong></td>
<td>-</td>
<td>-</td>
<td>-</td>
<td>1</td>
</tr>

</table>

<h3 id="returned_values">Returned Value(s) &nbsp;&nbsp;<a href="#"><img alt="picture" src="../pictures/up.png"/></a></h3>

<table class="arguments">

<tr>
<th>dim Value <span class="info"><a href="commonarguments.html#dim">[?]</a></span></th>
<th>single Value <span class="info"><a href="commonarguments.html#single">[?]</a></span></th>
<th>Type</th>
<th>Number</th>
<th>Name</th>
</tr>

<tr>
<td>0</td>
<td>False</td>
<td><strong>Vertex</strong></td>
<td>n</td>
<td><em>"EdgeOffset (Vertex)"</em></td>
</tr>

<tr>
<td>0</td>
<td>True</td>
<td><strong>Compound</strong> of <strong>Vertexes</strong></td>
<td>1</td>
<td><em>"EdgeOffset (Vertexes)"</em></td>
</tr>

<tr>
<td>1</td>
<td>False</td>
<td><strong>Edge</strong></td>
<td>3</td>
<td><em>"ClosedEdgeOffset (Edge)"</em></td>
</tr>

<tr>
<td>1</td>
<td>True</td>
<td><strong>Compound</strong> of <strong>Edges</strong></td>
<td>1</td>
<td><em>"EdgeOffset"</em> or <em>"ClosedEdgeOffset"</em></td>
</tr>

<tr>
<td>2</td>
<td>-</td>
<td><strong>Face</strong></td>
<td>1</td>
<td><em>"EdgeOffset (Face)"</em></td>
</tr>

</table>

<h3 id="example">Example &nbsp;&nbsp;<a href="#"><img alt="picture" src="../pictures/up.png"/></a></h3>

 

<p class="code">
from cfdmsh import * <strong># To adapt to the <a href = "use.html#import">cfdmsh installation method</a></strong><br/>
<br/>
vertex1 = geompy.MakeVertex(0, -30, 0)<br/>
vertex2 = geompy.MakeVertex(-30, 0, 0)<br/>
vertex3 = geompy.MakeVertex(0, 30, 0)<br/>
<br/>
arc = geompy.MakeArc(vertex1, vertex2, vertex3)<br/>
<br/>
face = geompy.MakePrismDXDYDZ2Ways(arc, -10, 0, 10)<br/>
<br/>
AddToStudy(arc, "arc")<br/>
AddToStudy(face, "face")<br/>
<br/>
<em>edge_offset_1 = MakeEdgeOffset(10, arc)</em><br/>
<em>edge_offset_2 = MakeEdgeOffset([10, 30], arc)</em><br/>
<em>edge_offset_3 = MakeEdgeOffset([10, 30, 20], arc, [0, 0.2, 1], rev = True)</em><br/>
<em>edge_offset_4 = MakeEdgeOffset(10, arc, face = face)</em><br/>
<em>edge_offset_5 = MakeEdgeOffset(10, arc, face = face, dim = 2)</em><br/>
</p>

 

<h3 id="conditions_of_use">Conditions of Use &nbsp;&nbsp;<a href="#"><img alt="picture" src="../pictures/up.png"/></a></h3>

<p>The input edge has to be open.</p>

<p>In addition, if the input edge is straight, it is also necessary to 
set the <em>face</em> or the <em>plane</em> argument so as the function knows the 
offset direction</p>

<p><a href="makefoilfromunsortedvertexes.html"><img alt="picture" src="../pictures/left.png"/> </a> &nbsp;&nbsp; <a href="makeplanarwireoffset.html"><img alt="picture" src="../pictures/right.png"/></a></p>

<p><a href="cfdmshfunctions.html"><img alt="picture" src="../pictures/back.png"></a>&nbsp;&nbsp;&nbsp;&nbsp;<a href="../index.html"><img alt="picture" src="../pictures/home.png"></a>&nbsp;&nbsp;&nbsp;<strong>cfdmsh 4.0 documentation</strong></p>

<p class="license"><a href="http://tougeron-cfd.com/">tougeron-cfd.com</a> Â© 2016</p>

	</body>
	
</html>